service: iamp

image: iamp-org/iamp

registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  server: ghcr.io
  username: spryffee
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Use a different ssh user than root
# ssh:
#   user: app

builder:
  args:
    RUBY_VERSION: 3.2.0
  remote:
    arch: amd64

healthcheck:
  path: /login
  port: 3000